name: release

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a new tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu to run Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker and pull Fedora
        run: |
          echo "Pulling Fedora image"
          docker pull fedora:latest  # Pull Fedora Docker image

      - name: Run build inside Fedora container
        run: |
          echo "Running build inside Fedora container"
          docker run -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest /bin/bash -c "
            dnf update -y &&
            dnf install -y gcc make bazelisk rpm-build &&
            chmod +x ./build.sh &&
            ./build.sh &&
            mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} &&
            cp ./stone-prover.spec ~/rpmbuild/SPECS/ &&
            rpmbuild -ba ~/rpmbuild/SPECS/stone-prover.spec --define '_topdir $HOME/rpmbuild' --define 'version ${GITHUB_REF#refs/tags/}' --define 'arch x86_64'
          "

      - name: Verify RPM
        run: |
          docker run fedora:latest ls -la ~/rpmbuild/RPMS/x86_64/  # List RPM to verify it was created

      - name: Upload RPM to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ~/rpmbuild/RPMS/x86_64/*.rpm
