name: Release Fedora Package

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a new tag is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: fedora-latest # Use Fedora environment for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      - name: Install dependencies
        run: |
          sudo dnf update -y
          sudo dnf install -y rpm-build gcc make bazel  # Install the required packages to build RPMs

      - name: Make build.sh executable
        run: chmod +x ./build.sh # Ensure build.sh is executable

      - name: Build using build.sh
        run: ./build.sh # Run the build script to compile your project

      - name: Prepare RPM directories
        run: mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} # Create the necessary directories for RPM build

      - name: Copy stone-prover.spec to SPECS
        run: cp ./stone-prover.spec ~/rpmbuild/SPECS/ # Copy the spec file to the SPECS directory

      - name: Package RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/stone-prover.spec \
            --define "_topdir $HOME/rpmbuild" \  # Define the top directory for the build
            --define "version ${GITHUB_REF#refs/tags/}" \  # Extract version from the GitHub tag
            --define "arch x86_64"  # Define the architecture

      - name: Verify RPM creation
        run: ls -la ~/rpmbuild/RPMS/x86_64/ # List the RPM files to verify the creation

      - name: Upload RPM to GitHub release
        uses: softprops/action-gh-release@v2 # Action to create a GitHub release
        with:
          files: ~/rpmbuild/RPMS/x86_64/*.rpm # Upload the RPM to the release
